# Generated by Django 3.2.6 on 2021-09-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20210911_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Workout_Songs',
        ),
        migrations.AddField(
            model_name='mix_songs',
            name='song_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='song_id_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.mix_songs'),
        ),
    ]
