# Generated by Django 3.2.6 on 2021-09-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20210927_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_songs',
            name='party_song_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='party_songs',
            name='song_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.mix_songs'),
        ),
    ]
