# Generated by Django 3.2.6 on 2021-09-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20210927_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chill_songs',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='chill_songs',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='chill_songs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chill_songs',
            name='title',
        ),
        migrations.AddField(
            model_name='chill_songs',
            name='chill_song_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chill_songs',
            name='song_chill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.mix_songs'),
        ),
    ]
