# Generated by Django 3.2.6 on 2021-09-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20210927_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix_songs',
            name='song_id',
        ),
    ]
