# Generated by Django 3.2.6 on 2021-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_auto_20210928_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arijit_singh',
            name='Arijit_Songs',
        ),
        migrations.RemoveField(
            model_name='arijit_singh',
            name='Arijit_Songs_extra',
        ),
        migrations.RemoveField(
            model_name='chill_songs',
            name='song_chill',
        ),
        migrations.RemoveField(
            model_name='extra_info',
            name='song_id_artist',
        ),
        migrations.RemoveField(
            model_name='jubin_nautiyal',
            name='Jubin_songs',
        ),
        migrations.RemoveField(
            model_name='jubin_nautiyal',
            name='Jubin_songs_extra',
        ),
        migrations.RemoveField(
            model_name='party_songs',
            name='song_party',
        ),
        migrations.AddField(
            model_name='mix_songs',
            name='artist_name',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='mix_songs',
            name='song_type',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AlterField(
            model_name='mix_songs',
            name='duration',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='A_R_Rahman',
        ),
        migrations.DeleteModel(
            name='Arijit_Singh',
        ),
        migrations.DeleteModel(
            name='Chill_Songs',
        ),
        migrations.DeleteModel(
            name='Extra_info',
        ),
        migrations.DeleteModel(
            name='Jubin_Nautiyal',
        ),
        migrations.DeleteModel(
            name='Party_Songs',
        ),
    ]
